//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolutionControlsInternal.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolutionControlsInternal.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Folder.
        /// </summary>
        public static string AddFolder {
            get {
                return ResourceManager.GetString("AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item.
        /// </summary>
        public static string AddItem {
            get {
                return ResourceManager.GetString("AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Tree.
        /// </summary>
        public static string AddTree {
            get {
                return ResourceManager.GetString("AddTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string ContextMenuAdd {
            get {
                return ResourceManager.GetString("ContextMenuAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Item....
        /// </summary>
        public static string ContextMenuAddExistingItemEllipsis {
            get {
                return ResourceManager.GetString("ContextMenuAddExistingItemEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        public static string ContextMenuAddNewFolder {
            get {
                return ResourceManager.GetString("ContextMenuAddNewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Solution.
        /// </summary>
        public static string ContextMenuDeleteSolution {
            get {
                return ResourceManager.GetString("ContextMenuDeleteSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string ContextMenuProperties {
            get {
                return ResourceManager.GetString("ContextMenuProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string ContextMenuRename {
            get {
                return ResourceManager.GetString("ContextMenuRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditToolBarName {
            get {
                return ResourceManager.GetString("EditToolBarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit ToolBar Options.
        /// </summary>
        public static string EditToolBarOptions {
            get {
                return ResourceManager.GetString("EditToolBarOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string FileToolBarName {
            get {
                return ResourceManager.GetString("FileToolBarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File ToolBar Options.
        /// </summary>
        public static string FileToolBarOptions {
            get {
                return ResourceManager.GetString("FileToolBarOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HelpToolBarName {
            get {
                return ResourceManager.GetString("HelpToolBarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help ToolBar Options.
        /// </summary>
        public static string HelpToolBarOptions {
            get {
                return ResourceManager.GetString("HelpToolBarOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string ProjectToolBarName {
            get {
                return ResourceManager.GetString("ProjectToolBarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project ToolBar Options.
        /// </summary>
        public static string ProjectToolBarOptions {
            get {
                return ResourceManager.GetString("ProjectToolBarOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Tree.
        /// </summary>
        public static string RemoveTree {
            get {
                return ResourceManager.GetString("RemoveTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (loading...).
        /// </summary>
        public static string SolutionTreeLoading {
            get {
                return ResourceManager.GetString("SolutionTreeLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Col.
        /// </summary>
        public static string StatusColumn {
            get {
                return ResourceManager.GetString("StatusColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        public static string StatusFailure {
            get {
                return ResourceManager.GetString("StatusFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing.
        /// </summary>
        public static string StatusInitializing {
            get {
                return ResourceManager.GetString("StatusInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INS.
        /// </summary>
        public static string StatusInsert {
            get {
                return ResourceManager.GetString("StatusInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ln.
        /// </summary>
        public static string StatusLine {
            get {
                return ResourceManager.GetString("StatusLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OVR.
        /// </summary>
        public static string StatusOverride {
            get {
                return ResourceManager.GetString("StatusOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {ApplicationName}....
        /// </summary>
        public static string ToolBarAboutEllipsis {
            get {
                return ResourceManager.GetString("ToolBarAboutEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {ApplicationName}.
        /// </summary>
        public static string ToolBarAboutToolTip {
            get {
                return ResourceManager.GetString("ToolBarAboutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Solution.
        /// </summary>
        public static string ToolBarBuildSolution {
            get {
                return ResourceManager.GetString("ToolBarBuildSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Solution.
        /// </summary>
        public static string ToolBarBuildSolutionToolTip {
            get {
                return ResourceManager.GetString("ToolBarBuildSolutionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string ToolBarClass {
            get {
                return ResourceManager.GetString("ToolBarClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close {0}.
        /// </summary>
        public static string ToolBarClose {
            get {
                return ResourceManager.GetString("ToolBarClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Solution.
        /// </summary>
        public static string ToolBarCloseSolution {
            get {
                return ResourceManager.GetString("ToolBarCloseSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Solution.
        /// </summary>
        public static string ToolBarCloseSolutionToolTip {
            get {
                return ResourceManager.GetString("ToolBarCloseSolutionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close {0}.
        /// </summary>
        public static string ToolBarCloseToolTip {
            get {
                return ResourceManager.GetString("ToolBarCloseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiler Output.
        /// </summary>
        public static string ToolBarCompilerOutputTool {
            get {
                return ResourceManager.GetString("ToolBarCompilerOutputTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the Compiler Output window.
        /// </summary>
        public static string ToolBarCompilerOutputToolToolTip {
            get {
                return ResourceManager.GetString("ToolBarCompilerOutputToolToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ToolBarEdit {
            get {
                return ResourceManager.GetString("ToolBarEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ToolBarExit {
            get {
                return ResourceManager.GetString("ToolBarExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ToolBarExitToolTip {
            get {
                return ResourceManager.GetString("ToolBarExitToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export All....
        /// </summary>
        public static string ToolBarExportAllEllipsis {
            get {
                return ResourceManager.GetString("ToolBarExportAllEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export All.
        /// </summary>
        public static string ToolBarExportAllToolTip {
            get {
                return ResourceManager.GetString("ToolBarExportAllToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export {0}....
        /// </summary>
        public static string ToolBarExportEllipsis {
            get {
                return ResourceManager.GetString("ToolBarExportEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Solution....
        /// </summary>
        public static string ToolBarExportSolutionEllipsis {
            get {
                return ResourceManager.GetString("ToolBarExportSolutionEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Solution.
        /// </summary>
        public static string ToolBarExportSolutionToolTip {
            get {
                return ResourceManager.GetString("ToolBarExportSolutionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export {0}.
        /// </summary>
        public static string ToolBarExportToolTip {
            get {
                return ResourceManager.GetString("ToolBarExportToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string ToolBarFile {
            get {
                return ResourceManager.GetString("ToolBarFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string ToolBarHelp {
            get {
                return ResourceManager.GetString("ToolBarHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import....
        /// </summary>
        public static string ToolBarImportEllipsis {
            get {
                return ResourceManager.GetString("ToolBarImportEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import solution....
        /// </summary>
        public static string ToolBarImportSolutionEllipsis {
            get {
                return ResourceManager.GetString("ToolBarImportSolutionEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import solution.
        /// </summary>
        public static string ToolBarImportSolutionToolTip {
            get {
                return ResourceManager.GetString("ToolBarImportSolutionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string ToolBarImportToolTip {
            get {
                return ResourceManager.GetString("ToolBarImportToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ToolBarInactiveClose {
            get {
                return ResourceManager.GetString("ToolBarInactiveClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ToolBarInactiveCloseToolTip {
            get {
                return ResourceManager.GetString("ToolBarInactiveCloseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export....
        /// </summary>
        public static string ToolBarInactiveExportEllipsis {
            get {
                return ResourceManager.GetString("ToolBarInactiveExportEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string ToolBarInactiveExportToolTip {
            get {
                return ResourceManager.GetString("ToolBarInactiveExportToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ToolBarInactiveSave {
            get {
                return ResourceManager.GetString("ToolBarInactiveSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as....
        /// </summary>
        public static string ToolBarInactiveSaveAsEllipsis {
            get {
                return ResourceManager.GetString("ToolBarInactiveSaveAsEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        public static string ToolBarInactiveSaveAsToolTip {
            get {
                return ResourceManager.GetString("ToolBarInactiveSaveAsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ToolBarInactiveSaveToolTip {
            get {
                return ResourceManager.GetString("ToolBarInactiveSaveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows....
        /// </summary>
        public static string ToolBarListWindows {
            get {
                return ResourceManager.GetString("ToolBarListWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List windows.
        /// </summary>
        public static string ToolBarListWindowsToolTip {
            get {
                return ResourceManager.GetString("ToolBarListWindowsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string ToolBarNew {
            get {
                return ResourceManager.GetString("ToolBarNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Solution.
        /// </summary>
        public static string ToolBarNewSolutionToolTip {
            get {
                return ResourceManager.GetString("ToolBarNewSolutionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Existing Item....
        /// </summary>
        public static string ToolBarOpenExistingEllipsis {
            get {
                return ResourceManager.GetString("ToolBarOpenExistingEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Existing Item.
        /// </summary>
        public static string ToolBarOpenExistingToolTip {
            get {
                return ResourceManager.GetString("ToolBarOpenExistingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Solution....
        /// </summary>
        public static string ToolBarOpenSolutionEllipsis {
            get {
                return ResourceManager.GetString("ToolBarOpenSolutionEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Solution.
        /// </summary>
        public static string ToolBarOpenSolutionToolTip {
            get {
                return ResourceManager.GetString("ToolBarOpenSolutionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options....
        /// </summary>
        public static string ToolBarOptionsEllipsis {
            get {
                return ResourceManager.GetString("ToolBarOptionsEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string ToolBarOptionsToolTip {
            get {
                return ResourceManager.GetString("ToolBarOptionsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string ToolBarProject {
            get {
                return ResourceManager.GetString("ToolBarProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string ToolBarPropertiesTool {
            get {
                return ResourceManager.GetString("ToolBarPropertiesTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show or hide the Properties window.
        /// </summary>
        public static string ToolBarPropertiesToolToolTip {
            get {
                return ResourceManager.GetString("ToolBarPropertiesToolToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Split.
        /// </summary>
        public static string ToolBarRemoveSplit {
            get {
                return ResourceManager.GetString("ToolBarRemoveSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Split.
        /// </summary>
        public static string ToolBarRemoveSplitToolTip {
            get {
                return ResourceManager.GetString("ToolBarRemoveSplitToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Layout.
        /// </summary>
        public static string ToolBarResetLayout {
            get {
                return ResourceManager.GetString("ToolBarResetLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Layout.
        /// </summary>
        public static string ToolBarResetLayoutToolTip {
            get {
                return ResourceManager.GetString("ToolBarResetLayoutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save {0}.
        /// </summary>
        public static string ToolBarSave {
            get {
                return ResourceManager.GetString("ToolBarSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save All.
        /// </summary>
        public static string ToolBarSaveAll {
            get {
                return ResourceManager.GetString("ToolBarSaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save All.
        /// </summary>
        public static string ToolBarSaveAllToolTip {
            get {
                return ResourceManager.GetString("ToolBarSaveAllToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save {0} as....
        /// </summary>
        public static string ToolBarSaveAsEllipsis {
            get {
                return ResourceManager.GetString("ToolBarSaveAsEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save {0} as.
        /// </summary>
        public static string ToolBarSaveAsToolTip {
            get {
                return ResourceManager.GetString("ToolBarSaveAsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save {0}.
        /// </summary>
        public static string ToolBarSaveToolTip {
            get {
                return ResourceManager.GetString("ToolBarSaveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution.
        /// </summary>
        public static string ToolBarSolution {
            get {
                return ResourceManager.GetString("ToolBarSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution Explorer.
        /// </summary>
        public static string ToolBarSolutionExplorerTool {
            get {
                return ResourceManager.GetString("ToolBarSolutionExplorerTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the Solution Explorer window.
        /// </summary>
        public static string ToolBarSolutionExplorerToolToolTip {
            get {
                return ResourceManager.GetString("ToolBarSolutionExplorerToolToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution Properties.
        /// </summary>
        public static string ToolBarSolutionProperties {
            get {
                return ResourceManager.GetString("ToolBarSolutionProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution Properties.
        /// </summary>
        public static string ToolBarSolutionPropertiesToolTip {
            get {
                return ResourceManager.GetString("ToolBarSolutionPropertiesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split.
        /// </summary>
        public static string ToolBarSplit {
            get {
                return ResourceManager.GetString("ToolBarSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split window horizontally.
        /// </summary>
        public static string ToolBarSplitToolTip {
            get {
                return ResourceManager.GetString("ToolBarSplitToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        public static string ToolBarWindow {
            get {
                return ResourceManager.GetString("ToolBarWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        public static string WindowToolBarName {
            get {
                return ResourceManager.GetString("WindowToolBarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window ToolBar Options.
        /// </summary>
        public static string WindowToolBarOptions {
            get {
                return ResourceManager.GetString("WindowToolBarOptions", resourceCulture);
            }
        }
    }
}
