//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolutionPresenterInternal.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolutionPresenterInternal.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        public static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Window(s).
        /// </summary>
        public static string CloseWindows {
            get {
                return ResourceManager.GetString("CloseWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiler.
        /// </summary>
        public static string Compiler {
            get {
                return ResourceManager.GetString("Compiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes made to &apos;{0}&apos;?.
        /// </summary>
        public static string ConfirmSaveDocumentChanges {
            get {
                return ResourceManager.GetString("ConfirmSaveDocumentChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes made to solution &apos;{0}&apos;?.
        /// </summary>
        public static string ConfirmSaveSolutionChanges {
            get {
                return ResourceManager.GetString("ConfirmSaveSolutionChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression.
        /// </summary>
        public static string Expression {
            get {
                return ResourceManager.GetString("Expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        public static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Folder and subfolders».
        /// </summary>
        public static string FolderAndSubfolders {
            get {
                return ResourceManager.GetString("FolderAndSubfolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metro.
        /// </summary>
        public static string Metro {
            get {
                return ResourceManager.GetString("Metro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}.
        /// </summary>
        public static string NameCopy {
            get {
                return ResourceManager.GetString("NameCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        public static string NewFolder {
            get {
                return ResourceManager.GetString("NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaged Solution.
        /// </summary>
        public static string PackagedSolutionFilter {
            get {
                return ResourceManager.GetString("PackagedSolutionFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace solution {0} and overwrite all current content?.
        /// </summary>
        public static string ReplaceSolution {
            get {
                return ResourceManager.GetString("ReplaceSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save all before compiling.
        /// </summary>
        public static string SaveBeforeCompiling {
            get {
                return ResourceManager.GetString("SaveBeforeCompiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save change to the following items?.
        /// </summary>
        public static string SaveChange {
            get {
                return ResourceManager.GetString("SaveChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution Explorer.
        /// </summary>
        public static string SolutionExplorer {
            get {
                return ResourceManager.GetString("SolutionExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution &apos;{0}&apos; and all its folders will be deleted permanently..
        /// </summary>
        public static string SolutionWillBeDeleted {
            get {
                return ResourceManager.GetString("SolutionWillBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace solution {0}?.
        /// </summary>
        public static string SolutionWillBeReplaced {
            get {
                return ResourceManager.GetString("SolutionWillBeReplaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        public static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Interface Theme.
        /// </summary>
        public static string UserInterfaceTheme {
            get {
                return ResourceManager.GetString("UserInterfaceTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Studio 2013.
        /// </summary>
        public static string VS2013 {
            get {
                return ResourceManager.GetString("VS2013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        public static string Windows {
            get {
                return ResourceManager.GetString("Windows", resourceCulture);
            }
        }
    }
}
